env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/jsx-uses-react: 0
  react/react-in-jsx-scope: 0
  react/prop-types: 0
  react/function-component-definition: [1, {
  namedComponents: "arrow-function"
  }]
